In [14]:
import pandas as pd

In [15]:
dados = pd.read_csv(r'C:\Users\Pichau\Downloads\Data Science Introdução ao Python Pandas\2 - Importando dados\aluguel.csv\aluguel.csv', sep = ';')
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0

In [ ]:
# Quantos imóveis existem na base de dados?
dados.value_counts('Tipo')\
    .sum()

# Resposta: Existem 32960 imóveis na nossa base de dados

np.int64(32960)

In [ ]:
# Quantos tipos diferentes de imóveis existem?
tipos_imovel = dados['Tipo']

# Resposta: Existem 22 tipos de imóveis

In [18]:
tipos_imovel.drop_duplicates()

0                          Quitinete
1                               Casa
2            Conjunto Comercial/Sala
3                        Apartamento
7                 Casa de Condomínio
16                    Prédio Inteiro
17                              Flat
29                        Loja/Salão
80           Galpão/Depósito/Armazém
83                    Casa Comercial
117                     Casa de Vila
159                   Terreno Padrão
207                      Box/Garagem
347                             Loft
589      Loja Shopping/ Ct Comercial
2157                         Chácara
3354           Loteamento/Condomínio
4379                           Sítio
4721                   Pousada/Chalé
6983                          Studio
9687                           Hotel
23614                      Indústria
Name: Tipo, dtype: object

In [19]:
tipos_imovel.drop_duplicates(inplace = True)

In [20]:
tipos_imovel.shape[0]

22

In [21]:
tipos_imovel.index = range(tipos_imovel.shape[0])
tipos_imovel

0                       Quitinete
1                            Casa
2         Conjunto Comercial/Sala
3                     Apartamento
4              Casa de Condomínio
5                  Prédio Inteiro
6                            Flat
7                      Loja/Salão
8         Galpão/Depósito/Armazém
9                  Casa Comercial
10                   Casa de Vila
11                 Terreno Padrão
12                    Box/Garagem
13                           Loft
14    Loja Shopping/ Ct Comercial
15                        Chácara
16          Loteamento/Condomínio
17                          Sítio
18                  Pousada/Chalé
19                         Studio
20                          Hotel
21                      Indústria
Name: Tipo, dtype: object

In [ ]:
# Qual é o bairro com a maior quantidade de imóveis cadastrados?
imoveis_por_bairro = dados['Bairro'].value_counts()
imoveis_por_bairro.head(1)

# Resposta: Bairro da Tijuca vence com a maior quantidade de imóveis cadastrados na base com 6259 imóveis

Bairro
Barra da Tijuca    6259
Name: count, dtype: int64

In [23]:
valor_medio = (
    dados.groupby('Tipo')['Valor']\
     .mean()\
     .reset_index()\
     .round(2)
)
valor_medio

                           Tipo      Valor
0                   Apartamento    4744.61
1                   Box/Garagem    1899.76
2                          Casa    6793.45
3                Casa Comercial   14478.26
4            Casa de Condomínio   11952.06
5                  Casa de Vila    1574.37
6                       Chácara    4900.00
7       Conjunto Comercial/Sala   14715.05
8                          Flat    4546.19
9       Galpão/Depósito/Armazém   53407.06
10                        Hotel   25000.00
11                    Indústria  120000.00
12                         Loft    2557.88
13  Loja Shopping/ Ct Comercial    8126.18
14                   Loja/Salão   13769.65
15        Loteamento/Condomínio   22000.00
16                Pousada/Chalé    1480.00
17               Prédio Inteiro  498637.24
18                    Quitinete    1246.84
19                       Studio    2400.00
20                        Sítio   12499.00
21               Terreno Padrão   32567.71

In [ ]:
# Qual é o imóvel mais caro e qual é o mais barato?
dados.sort_values(by='Valor', ascending=False).head(1)

# Resposta: O imóvel mais caro é Prédio Inteiro no bairro Jacarepaguá com o valor de 120000000.0

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
5592,Prédio Inteiro,Jacarepaguá,0,15,0,1200,120000000.0,NaN,10000.0

In [ ]:
dados.sort_values(by='Valor', ascending=True).head(1)

# Resposta: O imóvel mais barato é Galpão/Depósito/Armazém no bairro Taquara com o valor de 75.0

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
9452,Galpão/Depósito/Armazém,Taquara,0,0,0,150,75.0,NaN,NaN